spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    show-sql: false
  main:
    lazy-initialization: true
logging:
  level:
    web: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.orm.jpa: DEBUG

campsite:
  max-reserved-days: 3
  min-days-ahead-of-arrival: 1
  reservation-max-days-in-advance: 31

